#  Lab Reinforcement Learning
## Exercise 2: Q-Learning
谭树杰 11849060

In [2]:
import numpy as np
import copy
import gym
import random

In [7]:
env = gym.make("FrozenLake-v0")

/home/shu/PycharmProjects/RL/venv/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [11]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [12]:
total_episodes = 15000        
learning_rate = 0.8           
max_steps = 99                
gamma = 0.95                  

epsilon = 1.0                 
max_epsilon = 1.0             
min_epsilon = 0.01            
decay_rate = 0.005  

### Training

In [20]:
def train_qtable(env, total_episodes, max_steps, learning_rate, gamma,epsilon,,min_epsilon,max_epsilon,decay_rate):
    rewards = []
    qtable = np.zeros((state_size, action_size))
    for episode in range(total_episodes):

        state = env.reset()
        step = 0
        done = False
        total_rewards = 0

        for step in range(max_steps):
            prob = random.uniform(0, 1)
            if prob > epsilon:
                action = np.argmax(qtable[state, :]) # greedy
            else:
                action = env.action_space.sample() # explore
            new_state, reward, done, info = env.step(action)
            qtable[state, action] = qtable[state, action] + learning_rate * (
                reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
            total_rewards += reward
            state = new_state
            if done == True:
                break

        epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
        rewards.append(total_rewards)
    return qtable, rewards

In [21]:
qtable, rewards = train_qtable(env, total_episodes, max_steps, learning_rate, gamma,epsilon,,min_epsilon,max_epsilon,decay_rate)

In [22]:
print ("Average Score:" +  str(sum(rewards)/total_episodes))
print(qtable)

Average Score:0.4696
[[  2.36391978e-01   1.12828741e-01   1.00861971e-01   1.13336106e-01]
 [  2.52266646e-03   3.67714309e-03   8.33714525e-03   1.79903415e-01]
 [  8.83858923e-03   4.17504480e-02   8.94959711e-03   6.49521222e-02]
 [  4.67898952e-03   1.99650154e-03   1.64324616e-02   5.41143720e-02]
 [  1.85601333e-01   5.64284083e-02   8.34616356e-03   5.39768624e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.38644341e-04   5.82033827e-08   8.10938206e-05   4.13291771e-08]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.15369612e-04   9.94152202e-02   2.37868092e-03   1.35522788e-01]
 [  9.59320049e-03   3.47667575e-02   9.18089661e-03   9.43853183e-03]
 [  7.30735483e-01   6.53660411e-03   4.76148897e-03   5.50702667e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.43422753e-01   1.79509214e-02   1.46194780e-01   1

### Testing

In [23]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("-------------------------")
    print("EPISODE ", episode)

    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        if done:
            env.render()
            print("Number of steps", step)
            break
        state = new_state
env.close()

-------------------------
EPISODE  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 10
-------------------------
EPISODE  1
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 22
-------------------------
EPISODE  2
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 32
-------------------------
EPISODE  3
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 61
-------------------------
EPISODE  4
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
